# Generated by Django 3.1.5 on 2021-01-08 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('length', models.IntegerField(blank=True, choices=[(0, 'Short game'), (1, 'Medium game'), (2, 'Long game')])),
                ('hours', models.IntegerField(blank=True)),
                ('favorite', models.BooleanField(default=False)),
                ('total', models.FloatField(default=0.0)),
                ('ready', models.DateField(default=None, null=True, verbose_name='Run funded')),
                ('started', models.DateField(default=None, null=True, verbose_name='Run started')),
                ('ended', models.DateField(default=None, null=True, verbose_name='Run ended')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('slugname', models.SlugField(max_length=100)),
                ('donator_since', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('source', models.IntegerField(choices=[(0, 'Other source'), (1, 'Prime sub'), (2, 'Tier 1 sub'), (3, 'Tier 2 sub'), (4, 'Tier 3 sub'), (5, 'Bits'), (6, 'Direct donation'), (7, 'Patreon'), (8, 'Ad revenue')])),
                ('when', models.DateField(auto_now_add=True)),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lore2021.person')),
                ('during', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lore2021.game')),
                ('gifted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gifted_interest', to='lore2021.person')),
                ('interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='lore2021.game')),
            ],
        ),
    ]
