# Generated by Django 3.1.5 on 2021-01-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore2021', '0002_auto_20210108_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='slugname',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
