# Generated by Django 3.1.5 on 2021-01-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore2021', '0003_auto_20210108_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='length',
            new_name='glength',
        ),
        migrations.AlterField(
            model_name='donation',
            name='when',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
