# Generated by Django 3.1.5 on 2021-01-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore2021', '0004_auto_20210108_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
