# Generated by Django 3.1.5 on 2021-01-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore2021', '0005_game_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='funders',
            field=models.FloatField(default=0),
        ),
    ]
