# Generated by Django 3.1.5 on 2021-01-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore2021', '0006_auto_20210108_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='to_export',
            field=models.BooleanField(default=True, verbose_name='Export this game to the website'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='source',
            field=models.IntegerField(choices=[(0, 'Other source'), (1, 'Prime sub'), (2, 'Tier 1 sub'), (3, 'Tier 2 sub'), (4, 'Tier 3 sub'), (5, 'Bits'), (6, 'Direct donation'), (7, 'Patreon'), (8, 'Ad revenue'), (9, 'Imported')]),
        ),
    ]
