# Generated by Django 3.1.5 on 2021-01-10 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lore2021', '0008_auto_20210109_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.IntegerField(choices=[(0, "Allocated dealer's choice")], unique=True)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['slugname']},
        ),
        migrations.AlterField(
            model_name='donation',
            name='source',
            field=models.IntegerField(choices=[(0, 'Other source'), (1, 'Prime sub'), (2, 'Tier 1 sub'), (3, 'Tier 2 sub'), (4, 'Tier 3 sub'), (5, 'Bits'), (6, 'Direct donation'), (7, 'Patreon'), (8, 'Ad revenue'), (9, 'Imported'), (10, 'Dealer Choice input')]),
        ),
        migrations.AlterField(
            model_name='game',
            name='ended',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Run ended'),
        ),
        migrations.AlterField(
            model_name='game',
            name='ready',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Run funded'),
        ),
        migrations.AlterField(
            model_name='game',
            name='started',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Run started'),
        ),
        migrations.CreateModel(
            name='DealerChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lore2021.person')),
                ('during', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lore2021.game')),
            ],
        ),
    ]
