# Generated by Django 3.1.5 on 2021-01-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore2021', '0009_auto_20210110_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerchoice',
            name='source',
            field=models.IntegerField(choices=[(0, 'Other source'), (1, 'Prime sub'), (2, 'Tier 1 sub'), (3, 'Tier 2 sub'), (4, 'Tier 3 sub'), (5, 'Bits'), (6, 'Direct donation'), (7, 'Patreon'), (8, 'Ad revenue'), (9, 'Imported'), (10, 'Dealer Choice input'), (11, 'Lore credits')], default=0),
        ),
        migrations.AlterField(
            model_name='donation',
            name='source',
            field=models.IntegerField(choices=[(0, 'Other source'), (1, 'Prime sub'), (2, 'Tier 1 sub'), (3, 'Tier 2 sub'), (4, 'Tier 3 sub'), (5, 'Bits'), (6, 'Direct donation'), (7, 'Patreon'), (8, 'Ad revenue'), (9, 'Imported'), (10, 'Dealer Choice input'), (11, 'Lore credits')]),
        ),
        migrations.AlterField(
            model_name='variables',
            name='variable',
            field=models.IntegerField(choices=[(0, "Allocated dealer's choice"), (1, 'Priority multiplicator')], unique=True),
        ),
    ]
