# Generated by Django 3.2.5 on 2021-08-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore2021', '0011_alter_game_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='priority_needed',
            field=models.IntegerField(default=0),
        ),
    ]
