# Generated by Django 3.2.7 on 2021-09-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lore2021', '0012_game_priority_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='streamination',
            field=models.BooleanField(default=False),
        ),
    ]
